// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: search.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchClient interface {
	GetTechnologies(ctx context.Context, in *SearchText, opts ...grpc.CallOption) (*TechnologiesArr, error)
	GetTop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PositionTop, error)
	GetPositions(ctx context.Context, in *GetTechnology, opts ...grpc.CallOption) (*NodeInfo, error)
}

type searchClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchClient(cc grpc.ClientConnInterface) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) GetTechnologies(ctx context.Context, in *SearchText, opts ...grpc.CallOption) (*TechnologiesArr, error) {
	out := new(TechnologiesArr)
	err := c.cc.Invoke(ctx, "/search.Search/GetTechnologies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetTop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PositionTop, error) {
	out := new(PositionTop)
	err := c.cc.Invoke(ctx, "/search.Search/GetTop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetPositions(ctx context.Context, in *GetTechnology, opts ...grpc.CallOption) (*NodeInfo, error) {
	out := new(NodeInfo)
	err := c.cc.Invoke(ctx, "/search.Search/GetPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServer is the server API for Search service.
// All implementations should embed UnimplementedSearchServer
// for forward compatibility
type SearchServer interface {
	GetTechnologies(context.Context, *SearchText) (*TechnologiesArr, error)
	GetTop(context.Context, *Empty) (*PositionTop, error)
	GetPositions(context.Context, *GetTechnology) (*NodeInfo, error)
}

// UnimplementedSearchServer should be embedded to have forward compatible implementations.
type UnimplementedSearchServer struct {
}

func (UnimplementedSearchServer) GetTechnologies(context.Context, *SearchText) (*TechnologiesArr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTechnologies not implemented")
}
func (UnimplementedSearchServer) GetTop(context.Context, *Empty) (*PositionTop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTop not implemented")
}
func (UnimplementedSearchServer) GetPositions(context.Context, *GetTechnology) (*NodeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPositions not implemented")
}

// UnsafeSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServer will
// result in compilation errors.
type UnsafeSearchServer interface {
	mustEmbedUnimplementedSearchServer()
}

func RegisterSearchServer(s grpc.ServiceRegistrar, srv SearchServer) {
	s.RegisterService(&Search_ServiceDesc, srv)
}

func _Search_GetTechnologies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchText)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetTechnologies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.Search/GetTechnologies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetTechnologies(ctx, req.(*SearchText))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.Search/GetTop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetTop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTechnology)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.Search/GetPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetPositions(ctx, req.(*GetTechnology))
	}
	return interceptor(ctx, in, info, handler)
}

// Search_ServiceDesc is the grpc.ServiceDesc for Search service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Search_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTechnologies",
			Handler:    _Search_GetTechnologies_Handler,
		},
		{
			MethodName: "GetTop",
			Handler:    _Search_GetTop_Handler,
		},
		{
			MethodName: "GetPositions",
			Handler:    _Search_GetPositions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}