// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3c9d2b01DecodeMainInternalModels(in *jlexer.Lexer, out *ResumeRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "cv_text":
			out.CvText = string(in.String())
		case "n_tech":
			out.NTech = int(in.Int())
		case "n_prof":
			out.NProf = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeMainInternalModels(out *jwriter.Writer, in ResumeRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cv_text\":"
		out.RawString(prefix[1:])
		out.String(string(in.CvText))
	}
	{
		const prefix string = ",\"n_tech\":"
		out.RawString(prefix)
		out.Int(int(in.NTech))
	}
	{
		const prefix string = ",\"n_prof\":"
		out.RawString(prefix)
		out.Int(int(in.NProf))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResumeRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeMainInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResumeRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeMainInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResumeRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeMainInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResumeRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeMainInternalModels(l, v)
}
