// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD4176298DecodeMainInternalModels(in *jlexer.Lexer, out *Technology) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "technology_name":
			out.TechnologyName = string(in.String())
		case "distance":
			out.Distance = float32(in.Float32())
		case "professionalism":
			out.Professionalism = float32(in.Float32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD4176298EncodeMainInternalModels(out *jwriter.Writer, in Technology) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"technology_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.TechnologyName))
	}
	{
		const prefix string = ",\"distance\":"
		out.RawString(prefix)
		out.Float32(float32(in.Distance))
	}
	{
		const prefix string = ",\"professionalism\":"
		out.RawString(prefix)
		out.Float32(float32(in.Professionalism))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Technology) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD4176298EncodeMainInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Technology) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD4176298EncodeMainInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Technology) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD4176298DecodeMainInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Technology) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD4176298DecodeMainInternalModels(l, v)
}
func easyjsonD4176298DecodeMainInternalModels1(in *jlexer.Lexer, out *Profession) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "profession":
			out.Profession = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD4176298EncodeMainInternalModels1(out *jwriter.Writer, in Profession) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"profession\":"
		out.RawString(prefix[1:])
		out.String(string(in.Profession))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Profession) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD4176298EncodeMainInternalModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Profession) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD4176298EncodeMainInternalModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Profession) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD4176298DecodeMainInternalModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Profession) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD4176298DecodeMainInternalModels1(l, v)
}
func easyjsonD4176298DecodeMainInternalModels2(in *jlexer.Lexer, out *PositionData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "job_name":
			out.JobName = string(in.String())
		case "technology_number":
			out.TechnologyNumber = int(in.Int())
		case "additional":
			if in.IsNull() {
				in.Skip()
				out.Additional = nil
			} else {
				in.Delim('[')
				if out.Additional == nil {
					if !in.IsDelim(']') {
						out.Additional = make([]Technology, 0, 2)
					} else {
						out.Additional = []Technology{}
					}
				} else {
					out.Additional = (out.Additional)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Technology
					(v1).UnmarshalEasyJSON(in)
					out.Additional = append(out.Additional, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD4176298EncodeMainInternalModels2(out *jwriter.Writer, in PositionData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"job_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.JobName))
	}
	{
		const prefix string = ",\"technology_number\":"
		out.RawString(prefix)
		out.Int(int(in.TechnologyNumber))
	}
	{
		const prefix string = ",\"additional\":"
		out.RawString(prefix)
		if in.Additional == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Additional {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PositionData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD4176298EncodeMainInternalModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PositionData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD4176298EncodeMainInternalModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PositionData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD4176298DecodeMainInternalModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PositionData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD4176298DecodeMainInternalModels2(l, v)
}
